defaults:
  - base
  - env: crowdsim
  - model: ppo_base
  - trainer: ppo
  - _self_

model:
  actor:
    mlp:
      act: silu  # silu | tanh | relu

  critic:
    mlp:
      act: silu


wandb_interval: 100
