defaults:
  - base
  - env: crowdsim
  - model: ppo_base
  - trainer: ppo
  - _self_

model:
  actor:
    mlp:
      act: silu  # important!

  critic:
    mlp:
      act: silu # important!


wandb_interval: 10
