env_id: "social_nav_var_num_ploar"
type: "crowdsim"

topk: 5
farest_dist: 5

obs_dim: ${math:3+${env.topk}*4} # robot + topk humans
act_dim: 2

success_reward: 20
collision_penalty: -20
potential_factor: 3.0
constant_penalty: -0.025