# Dedicated Hydra config for eval/eval_test.py.
defaults:
  - env: crowdsim
  - model: default
  - _self_

actor_model: ???
algo: ""
test_mode: both
test_ep: 100
test_viz_ep: 50
eval_seed: 100
save_path: ""
render: false # render=True -> render_mode="human"/render=False -> render_mode="rgb_array"

hydra:
  job:
    chdir: false
